// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: das.proto

package com.alfred.service2;

public final class DASProto {
  private DASProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AnalysisRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:das.AnalysisRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string dataValue = 1;</code>
     */
    java.lang.String getDataValue();
    /**
     * <code>string dataValue = 1;</code>
     */
    com.google.protobuf.ByteString
        getDataValueBytes();

    /**
     * <code>string dataUnit = 2;</code>
     */
    java.lang.String getDataUnit();
    /**
     * <code>string dataUnit = 2;</code>
     */
    com.google.protobuf.ByteString
        getDataUnitBytes();

    /**
     * <code>int64 timestamp = 3;</code>
     */
    long getTimestamp();
  }
  /**
   * <pre>
   * The AnalysisRequest message contains 'dataValue', 'dataUnit', and 'timestamp'.
   * </pre>
   *
   * Protobuf type {@code das.AnalysisRequest}
   */
  public  static final class AnalysisRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:das.AnalysisRequest)
      AnalysisRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AnalysisRequest.newBuilder() to construct.
    private AnalysisRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AnalysisRequest() {
      dataValue_ = "";
      dataUnit_ = "";
      timestamp_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AnalysisRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              dataValue_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              dataUnit_ = s;
              break;
            }
            case 24: {

              timestamp_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.alfred.service2.DASProto.internal_static_das_AnalysisRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.alfred.service2.DASProto.internal_static_das_AnalysisRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.alfred.service2.DASProto.AnalysisRequest.class, com.alfred.service2.DASProto.AnalysisRequest.Builder.class);
    }

    public static final int DATAVALUE_FIELD_NUMBER = 1;
    private volatile java.lang.Object dataValue_;
    /**
     * <code>string dataValue = 1;</code>
     */
    public java.lang.String getDataValue() {
      java.lang.Object ref = dataValue_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dataValue_ = s;
        return s;
      }
    }
    /**
     * <code>string dataValue = 1;</code>
     */
    public com.google.protobuf.ByteString
        getDataValueBytes() {
      java.lang.Object ref = dataValue_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dataValue_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATAUNIT_FIELD_NUMBER = 2;
    private volatile java.lang.Object dataUnit_;
    /**
     * <code>string dataUnit = 2;</code>
     */
    public java.lang.String getDataUnit() {
      java.lang.Object ref = dataUnit_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dataUnit_ = s;
        return s;
      }
    }
    /**
     * <code>string dataUnit = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDataUnitBytes() {
      java.lang.Object ref = dataUnit_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dataUnit_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 3;
    private long timestamp_;
    /**
     * <code>int64 timestamp = 3;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getDataValueBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, dataValue_);
      }
      if (!getDataUnitBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, dataUnit_);
      }
      if (timestamp_ != 0L) {
        output.writeInt64(3, timestamp_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getDataValueBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, dataValue_);
      }
      if (!getDataUnitBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, dataUnit_);
      }
      if (timestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, timestamp_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.alfred.service2.DASProto.AnalysisRequest)) {
        return super.equals(obj);
      }
      com.alfred.service2.DASProto.AnalysisRequest other = (com.alfred.service2.DASProto.AnalysisRequest) obj;

      boolean result = true;
      result = result && getDataValue()
          .equals(other.getDataValue());
      result = result && getDataUnit()
          .equals(other.getDataUnit());
      result = result && (getTimestamp()
          == other.getTimestamp());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DATAVALUE_FIELD_NUMBER;
      hash = (53 * hash) + getDataValue().hashCode();
      hash = (37 * hash) + DATAUNIT_FIELD_NUMBER;
      hash = (53 * hash) + getDataUnit().hashCode();
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimestamp());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.alfred.service2.DASProto.AnalysisRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.alfred.service2.DASProto.AnalysisRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.alfred.service2.DASProto.AnalysisRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.alfred.service2.DASProto.AnalysisRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.alfred.service2.DASProto.AnalysisRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.alfred.service2.DASProto.AnalysisRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.alfred.service2.DASProto.AnalysisRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.alfred.service2.DASProto.AnalysisRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.alfred.service2.DASProto.AnalysisRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.alfred.service2.DASProto.AnalysisRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.alfred.service2.DASProto.AnalysisRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.alfred.service2.DASProto.AnalysisRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.alfred.service2.DASProto.AnalysisRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * The AnalysisRequest message contains 'dataValue', 'dataUnit', and 'timestamp'.
     * </pre>
     *
     * Protobuf type {@code das.AnalysisRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:das.AnalysisRequest)
        com.alfred.service2.DASProto.AnalysisRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.alfred.service2.DASProto.internal_static_das_AnalysisRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.alfred.service2.DASProto.internal_static_das_AnalysisRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.alfred.service2.DASProto.AnalysisRequest.class, com.alfred.service2.DASProto.AnalysisRequest.Builder.class);
      }

      // Construct using com.alfred.service2.DASProto.AnalysisRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        dataValue_ = "";

        dataUnit_ = "";

        timestamp_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.alfred.service2.DASProto.internal_static_das_AnalysisRequest_descriptor;
      }

      @java.lang.Override
      public com.alfred.service2.DASProto.AnalysisRequest getDefaultInstanceForType() {
        return com.alfred.service2.DASProto.AnalysisRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.alfred.service2.DASProto.AnalysisRequest build() {
        com.alfred.service2.DASProto.AnalysisRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.alfred.service2.DASProto.AnalysisRequest buildPartial() {
        com.alfred.service2.DASProto.AnalysisRequest result = new com.alfred.service2.DASProto.AnalysisRequest(this);
        result.dataValue_ = dataValue_;
        result.dataUnit_ = dataUnit_;
        result.timestamp_ = timestamp_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.alfred.service2.DASProto.AnalysisRequest) {
          return mergeFrom((com.alfred.service2.DASProto.AnalysisRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.alfred.service2.DASProto.AnalysisRequest other) {
        if (other == com.alfred.service2.DASProto.AnalysisRequest.getDefaultInstance()) return this;
        if (!other.getDataValue().isEmpty()) {
          dataValue_ = other.dataValue_;
          onChanged();
        }
        if (!other.getDataUnit().isEmpty()) {
          dataUnit_ = other.dataUnit_;
          onChanged();
        }
        if (other.getTimestamp() != 0L) {
          setTimestamp(other.getTimestamp());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.alfred.service2.DASProto.AnalysisRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.alfred.service2.DASProto.AnalysisRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object dataValue_ = "";
      /**
       * <code>string dataValue = 1;</code>
       */
      public java.lang.String getDataValue() {
        java.lang.Object ref = dataValue_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          dataValue_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string dataValue = 1;</code>
       */
      public com.google.protobuf.ByteString
          getDataValueBytes() {
        java.lang.Object ref = dataValue_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          dataValue_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string dataValue = 1;</code>
       */
      public Builder setDataValue(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        dataValue_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string dataValue = 1;</code>
       */
      public Builder clearDataValue() {
        
        dataValue_ = getDefaultInstance().getDataValue();
        onChanged();
        return this;
      }
      /**
       * <code>string dataValue = 1;</code>
       */
      public Builder setDataValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        dataValue_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object dataUnit_ = "";
      /**
       * <code>string dataUnit = 2;</code>
       */
      public java.lang.String getDataUnit() {
        java.lang.Object ref = dataUnit_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          dataUnit_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string dataUnit = 2;</code>
       */
      public com.google.protobuf.ByteString
          getDataUnitBytes() {
        java.lang.Object ref = dataUnit_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          dataUnit_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string dataUnit = 2;</code>
       */
      public Builder setDataUnit(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        dataUnit_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string dataUnit = 2;</code>
       */
      public Builder clearDataUnit() {
        
        dataUnit_ = getDefaultInstance().getDataUnit();
        onChanged();
        return this;
      }
      /**
       * <code>string dataUnit = 2;</code>
       */
      public Builder setDataUnitBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        dataUnit_ = value;
        onChanged();
        return this;
      }

      private long timestamp_ ;
      /**
       * <code>int64 timestamp = 3;</code>
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>int64 timestamp = 3;</code>
       */
      public Builder setTimestamp(long value) {
        
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 timestamp = 3;</code>
       */
      public Builder clearTimestamp() {
        
        timestamp_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:das.AnalysisRequest)
    }

    // @@protoc_insertion_point(class_scope:das.AnalysisRequest)
    private static final com.alfred.service2.DASProto.AnalysisRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.alfred.service2.DASProto.AnalysisRequest();
    }

    public static com.alfred.service2.DASProto.AnalysisRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AnalysisRequest>
        PARSER = new com.google.protobuf.AbstractParser<AnalysisRequest>() {
      @java.lang.Override
      public AnalysisRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AnalysisRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AnalysisRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AnalysisRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.alfred.service2.DASProto.AnalysisRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AnalysisResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:das.AnalysisResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string analyzedValue = 1;</code>
     */
    java.lang.String getAnalyzedValue();
    /**
     * <code>string analyzedValue = 1;</code>
     */
    com.google.protobuf.ByteString
        getAnalyzedValueBytes();

    /**
     * <code>string analysisSummary = 2;</code>
     */
    java.lang.String getAnalysisSummary();
    /**
     * <code>string analysisSummary = 2;</code>
     */
    com.google.protobuf.ByteString
        getAnalysisSummaryBytes();

    /**
     * <code>bool alert = 3;</code>
     */
    boolean getAlert();
  }
  /**
   * <pre>
   * The AnalysisResponse message contains 'analyzedValue', 'analysisSummary', and 'alert'.
   * </pre>
   *
   * Protobuf type {@code das.AnalysisResponse}
   */
  public  static final class AnalysisResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:das.AnalysisResponse)
      AnalysisResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AnalysisResponse.newBuilder() to construct.
    private AnalysisResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AnalysisResponse() {
      analyzedValue_ = "";
      analysisSummary_ = "";
      alert_ = false;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AnalysisResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              analyzedValue_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              analysisSummary_ = s;
              break;
            }
            case 24: {

              alert_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.alfred.service2.DASProto.internal_static_das_AnalysisResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.alfred.service2.DASProto.internal_static_das_AnalysisResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.alfred.service2.DASProto.AnalysisResponse.class, com.alfred.service2.DASProto.AnalysisResponse.Builder.class);
    }

    public static final int ANALYZEDVALUE_FIELD_NUMBER = 1;
    private volatile java.lang.Object analyzedValue_;
    /**
     * <code>string analyzedValue = 1;</code>
     */
    public java.lang.String getAnalyzedValue() {
      java.lang.Object ref = analyzedValue_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        analyzedValue_ = s;
        return s;
      }
    }
    /**
     * <code>string analyzedValue = 1;</code>
     */
    public com.google.protobuf.ByteString
        getAnalyzedValueBytes() {
      java.lang.Object ref = analyzedValue_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        analyzedValue_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ANALYSISSUMMARY_FIELD_NUMBER = 2;
    private volatile java.lang.Object analysisSummary_;
    /**
     * <code>string analysisSummary = 2;</code>
     */
    public java.lang.String getAnalysisSummary() {
      java.lang.Object ref = analysisSummary_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        analysisSummary_ = s;
        return s;
      }
    }
    /**
     * <code>string analysisSummary = 2;</code>
     */
    public com.google.protobuf.ByteString
        getAnalysisSummaryBytes() {
      java.lang.Object ref = analysisSummary_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        analysisSummary_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ALERT_FIELD_NUMBER = 3;
    private boolean alert_;
    /**
     * <code>bool alert = 3;</code>
     */
    public boolean getAlert() {
      return alert_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getAnalyzedValueBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, analyzedValue_);
      }
      if (!getAnalysisSummaryBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, analysisSummary_);
      }
      if (alert_ != false) {
        output.writeBool(3, alert_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getAnalyzedValueBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, analyzedValue_);
      }
      if (!getAnalysisSummaryBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, analysisSummary_);
      }
      if (alert_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, alert_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.alfred.service2.DASProto.AnalysisResponse)) {
        return super.equals(obj);
      }
      com.alfred.service2.DASProto.AnalysisResponse other = (com.alfred.service2.DASProto.AnalysisResponse) obj;

      boolean result = true;
      result = result && getAnalyzedValue()
          .equals(other.getAnalyzedValue());
      result = result && getAnalysisSummary()
          .equals(other.getAnalysisSummary());
      result = result && (getAlert()
          == other.getAlert());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ANALYZEDVALUE_FIELD_NUMBER;
      hash = (53 * hash) + getAnalyzedValue().hashCode();
      hash = (37 * hash) + ANALYSISSUMMARY_FIELD_NUMBER;
      hash = (53 * hash) + getAnalysisSummary().hashCode();
      hash = (37 * hash) + ALERT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getAlert());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.alfred.service2.DASProto.AnalysisResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.alfred.service2.DASProto.AnalysisResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.alfred.service2.DASProto.AnalysisResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.alfred.service2.DASProto.AnalysisResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.alfred.service2.DASProto.AnalysisResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.alfred.service2.DASProto.AnalysisResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.alfred.service2.DASProto.AnalysisResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.alfred.service2.DASProto.AnalysisResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.alfred.service2.DASProto.AnalysisResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.alfred.service2.DASProto.AnalysisResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.alfred.service2.DASProto.AnalysisResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.alfred.service2.DASProto.AnalysisResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.alfred.service2.DASProto.AnalysisResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * The AnalysisResponse message contains 'analyzedValue', 'analysisSummary', and 'alert'.
     * </pre>
     *
     * Protobuf type {@code das.AnalysisResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:das.AnalysisResponse)
        com.alfred.service2.DASProto.AnalysisResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.alfred.service2.DASProto.internal_static_das_AnalysisResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.alfred.service2.DASProto.internal_static_das_AnalysisResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.alfred.service2.DASProto.AnalysisResponse.class, com.alfred.service2.DASProto.AnalysisResponse.Builder.class);
      }

      // Construct using com.alfred.service2.DASProto.AnalysisResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        analyzedValue_ = "";

        analysisSummary_ = "";

        alert_ = false;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.alfred.service2.DASProto.internal_static_das_AnalysisResponse_descriptor;
      }

      @java.lang.Override
      public com.alfred.service2.DASProto.AnalysisResponse getDefaultInstanceForType() {
        return com.alfred.service2.DASProto.AnalysisResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.alfred.service2.DASProto.AnalysisResponse build() {
        com.alfred.service2.DASProto.AnalysisResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.alfred.service2.DASProto.AnalysisResponse buildPartial() {
        com.alfred.service2.DASProto.AnalysisResponse result = new com.alfred.service2.DASProto.AnalysisResponse(this);
        result.analyzedValue_ = analyzedValue_;
        result.analysisSummary_ = analysisSummary_;
        result.alert_ = alert_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.alfred.service2.DASProto.AnalysisResponse) {
          return mergeFrom((com.alfred.service2.DASProto.AnalysisResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.alfred.service2.DASProto.AnalysisResponse other) {
        if (other == com.alfred.service2.DASProto.AnalysisResponse.getDefaultInstance()) return this;
        if (!other.getAnalyzedValue().isEmpty()) {
          analyzedValue_ = other.analyzedValue_;
          onChanged();
        }
        if (!other.getAnalysisSummary().isEmpty()) {
          analysisSummary_ = other.analysisSummary_;
          onChanged();
        }
        if (other.getAlert() != false) {
          setAlert(other.getAlert());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.alfred.service2.DASProto.AnalysisResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.alfred.service2.DASProto.AnalysisResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object analyzedValue_ = "";
      /**
       * <code>string analyzedValue = 1;</code>
       */
      public java.lang.String getAnalyzedValue() {
        java.lang.Object ref = analyzedValue_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          analyzedValue_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string analyzedValue = 1;</code>
       */
      public com.google.protobuf.ByteString
          getAnalyzedValueBytes() {
        java.lang.Object ref = analyzedValue_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          analyzedValue_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string analyzedValue = 1;</code>
       */
      public Builder setAnalyzedValue(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        analyzedValue_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string analyzedValue = 1;</code>
       */
      public Builder clearAnalyzedValue() {
        
        analyzedValue_ = getDefaultInstance().getAnalyzedValue();
        onChanged();
        return this;
      }
      /**
       * <code>string analyzedValue = 1;</code>
       */
      public Builder setAnalyzedValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        analyzedValue_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object analysisSummary_ = "";
      /**
       * <code>string analysisSummary = 2;</code>
       */
      public java.lang.String getAnalysisSummary() {
        java.lang.Object ref = analysisSummary_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          analysisSummary_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string analysisSummary = 2;</code>
       */
      public com.google.protobuf.ByteString
          getAnalysisSummaryBytes() {
        java.lang.Object ref = analysisSummary_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          analysisSummary_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string analysisSummary = 2;</code>
       */
      public Builder setAnalysisSummary(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        analysisSummary_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string analysisSummary = 2;</code>
       */
      public Builder clearAnalysisSummary() {
        
        analysisSummary_ = getDefaultInstance().getAnalysisSummary();
        onChanged();
        return this;
      }
      /**
       * <code>string analysisSummary = 2;</code>
       */
      public Builder setAnalysisSummaryBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        analysisSummary_ = value;
        onChanged();
        return this;
      }

      private boolean alert_ ;
      /**
       * <code>bool alert = 3;</code>
       */
      public boolean getAlert() {
        return alert_;
      }
      /**
       * <code>bool alert = 3;</code>
       */
      public Builder setAlert(boolean value) {
        
        alert_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool alert = 3;</code>
       */
      public Builder clearAlert() {
        
        alert_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:das.AnalysisResponse)
    }

    // @@protoc_insertion_point(class_scope:das.AnalysisResponse)
    private static final com.alfred.service2.DASProto.AnalysisResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.alfred.service2.DASProto.AnalysisResponse();
    }

    public static com.alfred.service2.DASProto.AnalysisResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AnalysisResponse>
        PARSER = new com.google.protobuf.AbstractParser<AnalysisResponse>() {
      @java.lang.Override
      public AnalysisResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AnalysisResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AnalysisResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AnalysisResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.alfred.service2.DASProto.AnalysisResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_das_AnalysisRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_das_AnalysisRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_das_AnalysisResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_das_AnalysisResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tdas.proto\022\003das\"I\n\017AnalysisRequest\022\021\n\td" +
      "ataValue\030\001 \001(\t\022\020\n\010dataUnit\030\002 \001(\t\022\021\n\ttime" +
      "stamp\030\003 \001(\003\"Q\n\020AnalysisResponse\022\025\n\ranaly" +
      "zedValue\030\001 \001(\t\022\027\n\017analysisSummary\030\002 \001(\t\022" +
      "\r\n\005alert\030\003 \001(\0102S\n\023DataAnalysisService\022<\n" +
      "\013AnalyzeData\022\024.das.AnalysisRequest\032\025.das" +
      ".AnalysisResponse\"\000B!\n\023com.alfred.servic" +
      "e2B\010DASProtoP\000b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_das_AnalysisRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_das_AnalysisRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_das_AnalysisRequest_descriptor,
        new java.lang.String[] { "DataValue", "DataUnit", "Timestamp", });
    internal_static_das_AnalysisResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_das_AnalysisResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_das_AnalysisResponse_descriptor,
        new java.lang.String[] { "AnalyzedValue", "AnalysisSummary", "Alert", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
